project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "QCBS Workshop: the secret weapon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

execute: 
  freeze: true

